// <auto-generated />
using System;
using LogicMonitor.Datamart;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicMonitor.Datamart.Migrations.SqlServerMigrations
{
	[DbContext(typeof(SqlServerContext))]
	[Migration("20250426171006_UpdatedConfigSourceAndDataSource")]
	partial class UpdatedConfigSourceAndDataSource
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "9.0.2")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AlertRuleStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("DataPoint")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DataSourceInstanceName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DataSourceName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<Guid>("EscalationChainId")
						.HasColumnType("uniqueidentifier");

					b.Property<int>("EscalationChainIntervalMinutes")
						.HasColumnType("int");

					b.Property<string>("LevelString")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Priority")
						.HasColumnType("int");

					b.Property<bool>("SuppressAlertAckSdt")
						.HasColumnType("bit");

					b.Property<bool>("SuppressAlertClear")
						.HasColumnType("bit");

					b.HasKey("Id");

					b.HasIndex("EscalationChainId");

					b.ToTable("AlertRules");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AlertStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AckComment")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<bool>("Acked")
						.HasColumnType("bit");

					b.Property<string>("AckedBy")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("AckedOnSeconds")
						.HasColumnType("int");

					b.Property<string>("ActiveDiscoveryAlertDescription")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("AlertEscalationChainId")
						.HasColumnType("int");

					b.Property<string>("AlertEscalationChainName")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("AlertEscalationSubChainId")
						.HasColumnType("int");

					b.Property<string>("AlertRecipients")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<Guid?>("AlertRuleId")
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AlertRuleName")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("AlertType")
						.HasColumnType("int");

					b.Property<string>("ClearValue")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CustomColumn1")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CustomColumn2")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CustomColumn3")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CustomColumn4")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CustomColumn5")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("DataPointId")
						.HasColumnType("int");

					b.Property<string>("DataPointName")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<string>("DependencyRole")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("DependencyRoutingState")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("DetailMessageBody")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("DetailMessageSubject")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("EnableAnomalyAlertGeneration")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("EnableAnomalyAlertSuppression")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("EndOnSeconds")
						.HasColumnType("int");

					b.Property<bool>("InScheduledDownTime")
						.HasColumnType("bit");

					b.Property<string>("InstanceDescription")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<int>("InstanceId")
						.HasColumnType("int");

					b.Property<string>("InstanceName")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("InternalId")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<bool>("IsActiveDiscoveryAlert")
						.HasMaxLength(50)
						.HasColumnType("bit");

					b.Property<bool>("IsAnomaly")
						.HasColumnType("bit");

					b.Property<bool>("IsCleared")
						.HasColumnType("bit");

					b.Property<string>("LogicMonitorId")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<Guid?>("MonitorObjectGroup0Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup1Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup2Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup3Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup4Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup5Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup6Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup7Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup8Id")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("MonitorObjectGroup9Id")
						.HasColumnType("uniqueidentifier");

					b.Property<int?>("MonitorObjectId")
						.HasColumnType("int");

					b.Property<string>("MonitorObjectName")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("MonitorObjectType")
						.HasColumnType("int");

					b.Property<int>("NextRecipient")
						.HasColumnType("int");

					b.Property<int?>("ResourceId")
						.HasColumnType("int");

					b.Property<int?>("ResourceTemplateId")
						.HasColumnType("int");

					b.Property<string>("ResourceTemplateName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ResourceTemplateType")
						.HasMaxLength(10)
						.HasColumnType("nvarchar(10)");

					b.Property<int>("Severity")
						.HasColumnType("int");

					b.Property<int>("StartOnSeconds")
						.HasColumnType("int");

					b.Property<string>("SuppressedDescending")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Suppressor")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Tenant")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Thresholds")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Value")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.HasKey("Id");

					b.HasIndex("AlertRuleId");

					b.HasIndex("DataPointId");

					b.HasIndex("DataPointName");

					b.HasIndex("EndOnSeconds");

					b.HasIndex("Id");

					b.HasIndex("InstanceId");

					b.HasIndex("InstanceName");

					b.HasIndex("InternalId");

					b.HasIndex("IsCleared");

					b.HasIndex("MonitorObjectGroup0Id");

					b.HasIndex("MonitorObjectGroup1Id");

					b.HasIndex("MonitorObjectGroup2Id");

					b.HasIndex("MonitorObjectGroup3Id");

					b.HasIndex("MonitorObjectGroup4Id");

					b.HasIndex("MonitorObjectGroup5Id");

					b.HasIndex("MonitorObjectGroup6Id");

					b.HasIndex("MonitorObjectGroup7Id");

					b.HasIndex("MonitorObjectGroup8Id");

					b.HasIndex("MonitorObjectGroup9Id");

					b.HasIndex("MonitorObjectId");

					b.HasIndex("MonitorObjectName");

					b.HasIndex("MonitorObjectType");

					b.HasIndex("ResourceId");

					b.HasIndex("ResourceTemplateId");

					b.HasIndex("ResourceTemplateName");

					b.HasIndex("ResourceTemplateType");

					b.HasIndex("Severity");

					b.HasIndex("StartOnSeconds");

					b.HasIndex("StartOnSeconds", "EndOnSeconds", "IsCleared", "InScheduledDownTime", "MonitorObjectGroup0Id", "MonitorObjectGroup1Id", "MonitorObjectGroup2Id", "MonitorObjectGroup3Id", "MonitorObjectGroup4Id", "MonitorObjectGroup5Id", "MonitorObjectGroup6Id", "MonitorObjectGroup7Id", "MonitorObjectGroup8Id", "MonitorObjectGroup9Id")
						.HasDatabaseName("IX_Alerts_FasterPercentageAvailability");

					SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StartOnSeconds", "EndOnSeconds", "IsCleared", "InScheduledDownTime", "MonitorObjectGroup0Id", "MonitorObjectGroup1Id", "MonitorObjectGroup2Id", "MonitorObjectGroup3Id", "MonitorObjectGroup4Id", "MonitorObjectGroup5Id", "MonitorObjectGroup6Id", "MonitorObjectGroup7Id", "MonitorObjectGroup8Id", "MonitorObjectGroup9Id"), new[] { "Id", "Severity", "ClearValue", "MonitorObjectId", "ResourceTemplateName", "InstanceId", "InstanceName" });

					b.ToTable("Alerts");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AuditEventStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("ActionType")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("AlertId")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("AlertNote")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ApiMethod")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ApiPath")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ApiTokenId")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("CollectorDescription")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("CollectorGroupId")
						.HasColumnType("int");

					b.Property<string>("CollectorGroupName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("CollectorId")
						.HasColumnType("int");

					b.Property<string>("CollectorName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Command")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("DataSourceDeletedInstanceIds")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("DataSourceDeletedInstanceNames")
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("DataSourceNewInstanceIds")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("DataSourceNewInstanceNames")
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DateTime")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<int?>("DeviceDataSourceId")
						.HasColumnType("int");

					b.Property<string>("EndDownTime")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("EntityType")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Host")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("InstanceId")
						.HasColumnType("int");

					b.Property<string>("InstanceName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("LogicModuleId")
						.HasColumnType("int");

					b.Property<string>("LogicModuleName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("LogicModuleVersion")
						.HasColumnType("int");

					b.Property<string>("LogicMonitorId")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("MatchedRegExId")
						.HasColumnType("int");

					b.Property<long?>("MonthlyMetrics")
						.HasColumnType("bigint");

					b.Property<string>("OriginalDescription")
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("OriginatorType")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("OutcomeType")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PerformedByUsername")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PropertyName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("PropertyValue")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<long?>("RemoteSessionId")
						.HasMaxLength(50)
						.HasColumnType("bigint");

					b.Property<string>("RemoteSessionType")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<long?>("RequestId")
						.HasColumnType("bigint");

					b.Property<int?>("ResourceGroupId")
						.HasColumnType("int");

					b.Property<string>("ResourceGroupName")
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<string>("ResourceHostname")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ResourceIds")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("ResourceNames")
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<bool?>("RestrictSso")
						.HasMaxLength(50)
						.HasColumnType("bit");

					b.Property<string>("SessionId")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("StartDownTime")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Time")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("UserEmail")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int?>("UserId")
						.HasColumnType("int");

					b.Property<string>("UserName")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("UserRole")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("WildValue")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.HasKey("Id");

					b.ToTable("AuditEvents");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.CollectorGroupStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("CollectorCount")
						.HasColumnType("int");

					b.Property<long>("CreatedOnTimeStampSeconds")
						.HasColumnType("bigint");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("CollectorGroups");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.CollectorStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AckComment")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("Acked")
						.HasColumnType("bit");

					b.Property<string>("AckedBy")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckedOnLocalString")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long?>("AckedOnUtcTimestampUtc")
						.HasColumnType("bigint");

					b.Property<string>("Architecture")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("BackupCollectorId")
						.HasColumnType("int");

					b.Property<int>("Build")
						.HasColumnType("int");

					b.Property<bool>("CanDowngrade")
						.HasColumnType("bit");

					b.Property<string>("CanDowngradeReason")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("ClearSent")
						.HasColumnType("bit");

					b.Property<string>("CollectorConfiguration")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<Guid>("CollectorGroupId")
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Configuration")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ConfigurationVersion")
						.HasColumnType("int");

					b.Property<string>("CreatedOnLocalString")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long>("CreatedOnTimeStampUtc")
						.HasColumnType("bigint");

					b.Property<string>("Credential")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Credential2")
						.HasColumnType("nvarchar(max)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("DeviceCount")
						.HasColumnType("int");

					b.Property<bool>("Ea")
						.HasColumnType("bit");

					b.Property<bool>("EnableFailBack")
						.HasColumnType("bit");

					b.Property<bool>("EnableFailOverOnCollectorDevice")
						.HasColumnType("bit");

					b.Property<int>("EscalationChainId")
						.HasColumnType("int");

					b.Property<bool>("HasFailOverDevice")
						.HasColumnType("bit");

					b.Property<string>("HostName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("InSdt")
						.HasColumnType("bit");

					b.Property<bool>("IsDown")
						.HasColumnType("bit");

					b.Property<bool>("IsEncoded")
						.HasColumnType("bit");

					b.Property<bool>("IsLmLogsEnabled")
						.HasColumnType("bit");

					b.Property<bool>("IsLmLogsSyslogEnabled")
						.HasColumnType("bit");

					b.Property<string>("LastSentNotificationOnLocal")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LastSentNotificationOnTimeStampUtc")
						.HasColumnType("int");

					b.Property<int>("LogicMonitorDeviceId")
						.HasColumnType("int");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("NeedAutoCreateCollectorDevice")
						.HasColumnType("bit");

					b.Property<int>("NetscanVersion")
						.HasColumnType("int");

					b.Property<int>("NextRecipient")
						.HasColumnType("int");

					b.Property<string>("OnetimeDowngradeInfo")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OtelVersion")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Platform")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("PreviousVersion")
						.HasColumnType("int");

					b.Property<string>("ProxyConfiguration")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ResendIntervalSeconds")
						.HasColumnType("int");

					b.Property<string>("Size")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("SpecifiedCollectorDeviceGroupId")
						.HasColumnType("int");

					b.Property<int>("Status")
						.HasColumnType("int");

					b.Property<bool>("SuppressAlertClear")
						.HasColumnType("bit");

					b.Property<string>("UpdatedOnLocalString")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long?>("UpdatedOnTimeStampUtc")
						.HasColumnType("bigint");

					b.Property<long>("UpgradeTimeUtcSeconds")
						.HasColumnType("bigint");

					b.Property<int>("UptimeSeconds")
						.HasColumnType("int");

					b.Property<string>("UserChangeOnLocal")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long>("UserChangeOnUtcSeconds")
						.HasColumnType("bigint");

					b.Property<int>("UserPermission")
						.HasColumnType("int");

					b.Property<int>("UserVisibleDeviceCount")
						.HasColumnType("int");

					b.Property<int>("UserVisibleWebsiteCount")
						.HasColumnType("int");

					b.Property<string>("WatchdogConfiguration")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("WatchdogUpdatedOnLocal")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long?>("WatchdogUpdatedOnSeconds")
						.HasColumnType("bigint");

					b.Property<string>("WebsiteConfiguration")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("WebsiteCount")
						.HasColumnType("int");

					b.Property<string>("WrapperConfiguration")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.HasIndex("CollectorGroupId");

					b.ToTable("Collectors");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ConfigSourceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AppliesTo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AuditVersion")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Checksum")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("CollectionMethod")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DisplayName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Group")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Version")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("ConfigSources");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceDataPointStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Calculation")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<Guid?>("DataSourceGraphId")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("DataSourceGraphStoreItemId")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid>("DataSourceId")
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("GlobalAlertExpression")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("MeasurementUnit")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PercentageAvailabilityCalculation")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property1")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property10")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property2")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property3")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property4")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property5")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property6")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property7")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property8")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property9")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("ResyncTimeSeriesData")
						.HasColumnType("bit");

					b.Property<string>("Tags")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.HasIndex("DataSourceGraphStoreItemId");

					b.HasIndex("DataSourceId");

					b.ToTable("DataSourceDataPoints");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceGraphStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<Guid>("DataSourceId")
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<int>("DisplayPriority")
						.HasColumnType("int");

					b.Property<int>("Height")
						.HasColumnType("int");

					b.Property<bool>("IsBase1024")
						.HasColumnType("bit");

					b.Property<bool>("IsOverview")
						.HasColumnType("bit");

					b.Property<bool>("IsRigid")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<double?>("MaxValue")
						.HasColumnType("float");

					b.Property<double?>("MinValue")
						.HasColumnType("float");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Timescale")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Title")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("VerticalLabel")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Width")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("DataSourceId");

					b.ToTable("DataSourceGraphs");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AppliesTo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AuditVersion")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Checksum")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("CollectionAttributeIp")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("CollectionAttributeName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("CollectionMethod")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DisplayName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Group")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("HasMultiInstances")
						.HasColumnType("bit");

					b.Property<string>("InstallationMetadataAuditedRegistryId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataAuditedVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<bool?>("InstallationMetadataIsChangedFromOrigin")
						.HasColumnType("bit");

					b.Property<bool?>("InstallationMetadataIsChangedFromTargetLastPublished")
						.HasColumnType("bit");

					b.Property<int?>("InstallationMetadataLogicModuleId")
						.HasColumnType("int");

					b.Property<string>("InstallationMetadataLogicModuleType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginAuthorCompanyUuid")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginAuthorNamespace")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginChecksum")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginLineageId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginRegistryId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataOriginVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataTargetLastPublishedChecksum")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataTargetLastPublishedId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataTargetLastPublishedVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstallationMetadataTargetLineageId")
						.HasColumnType("nvarchar(max)");

					b.Property<long?>("LastTimeSeriesDataSyncDurationMs")
						.HasColumnType("bigint");

					b.Property<string>("LineageId")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PayloadVersion")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("PollingIntervalSeconds")
						.HasColumnType("int");

					b.Property<string>("Tags")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Technology")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("UseWildValueAsUuid")
						.HasColumnType("bit");

					b.Property<string>("Version")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("DataSources");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.EscalationChainStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("CcDestination")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("CcDestinations")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Destination")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Destinations")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("EnableThrottling")
						.HasColumnType("bit");

					b.Property<bool>("InAlerting")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ThrottlingAlertCount")
						.HasColumnType("int");

					b.Property<int>("ThrottlingPeriodMinutes")
						.HasColumnType("int");

					b.HasKey("Id");

					b.ToTable("EscalationChains");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.EventSourceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("EventSources");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.IntegrationStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int?>("AccountId")
						.HasColumnType("int");

					b.Property<string>("AckAlertDataType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckHeaders")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckMethod")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthAccessTokenUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthClientId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthClientSecret")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthGrantType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthScope")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckOAuthVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckPassword")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckPayload")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckPayloadFormat")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AckUsername")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AlertDataType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Body")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearAlertDataType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearHeaders")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearMethod")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthAccessTokenUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthClientId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthClientSecret")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthGrantType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthScope")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearOAuthVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearPassword")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearPayload")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearPayloadFormat")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClearUsername")
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("CriticalPriority")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DueDateTime")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("EnabledStatus")
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("ErrorPriority")
						.HasColumnType("int");

					b.Property<string>("Extra")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Headers")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Method")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthAccessTokenUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthClientId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthClientSecret")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthGrantType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthScope")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("OAuthVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ParseExpression")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ParseMethod")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Password")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Payload")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PayloadFormat")
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("QueueId")
						.HasColumnType("int");

					b.Property<string>("Receivers")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Sender")
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("StatusAckTicket")
						.HasColumnType("int");

					b.Property<int?>("StatusCloseTicket")
						.HasColumnType("int");

					b.Property<int?>("StatusNewTicket")
						.HasColumnType("int");

					b.Property<int?>("StatusUpdateTicket")
						.HasColumnType("int");

					b.Property<string>("Subject")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateAlertDataType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataAlertDataType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataHeaders")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataMethod")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthAccessTokenUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthClientId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthClientSecret")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthGrantType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthScope")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataOAuthVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataPassword")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataPayload")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataPayloadFormat")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateDataUsername")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateHeaders")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateMethod")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthAccessTokenUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthClientId")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthClientSecret")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthGrantType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthScope")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateOAuthVersion")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdatePassword")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdatePayload")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdatePayloadFormat")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateUrl")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UpdateUsername")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Url")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Username")
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("WarnPriority")
						.HasColumnType("int");

					b.Property<int?>("Zone")
						.HasColumnType("int");

					b.HasKey("Id");

					b.ToTable("Integrations");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.LogStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long>("HappenedOnTimeStampUtc")
						.HasColumnType("bigint");

					b.Property<string>("IpAddress")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("LogicMonitorId")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("SessionId")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("UserName")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.HasKey("Id");

					b.ToTable("LogItems");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.LogicModuleUpdateStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<string>("AppliesTo")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<long>("AuditVersion")
						.HasColumnType("bigint");

					b.Property<string>("Category")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("CollectionMethod")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("CurrentUuid")
						.IsRequired()
						.HasMaxLength(30)
						.HasColumnType("nvarchar(30)");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTime>("DatamartLastObserved")
						.HasColumnType("datetime2");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("Group")
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<string>("Local")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<int>("LocalId")
						.HasColumnType("int");

					b.Property<long>("LocalVersion")
						.HasColumnType("bigint");

					b.Property<string>("Locator")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("Namespace")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("nvarchar(50)");

					b.Property<long>("PublishedAtMilliseconds")
						.HasColumnType("bigint");

					b.Property<string>("Quality")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("RegistryVersion")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<string>("Remote")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("nvarchar(1000)");

					b.Property<string>("RestLm")
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<string>("Type")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("nvarchar(20)");

					b.Property<long>("Version")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.ToTable("LogicModuleUpdates");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<string>("FullPath")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("nvarchar(200)");

					b.Property<int>("MonitoredObjectType")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("FullPath", "MonitoredObjectType");

					b.ToTable("MonitorObjectGroups");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceDataPointStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset?>("DataCompleteTo")
						.HasColumnType("datetimeoffset");

					b.Property<Guid>("DataSourceDataPointId")
						.HasColumnType("uniqueidentifier");

					b.Property<Guid?>("DataSourceStoreItemId")
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<Guid>("DeviceDataSourceInstanceId")
						.HasColumnType("uniqueidentifier");

					b.Property<string>("InstanceDatapointProperty1")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty10")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty2")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty3")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty4")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty5")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty6")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty7")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty8")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceDatapointProperty9")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("DataSourceDataPointId");

					b.HasIndex("DataSourceStoreItemId");

					b.HasIndex("DeviceDataSourceInstanceId");

					b.ToTable("DeviceDataSourceInstanceDataPoints");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("AlertDisableStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatusPriority")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<Guid>("DeviceDataSourceId")
						.HasColumnType("uniqueidentifier");

					b.Property<bool>("DisableAlerting")
						.HasColumnType("bit");

					b.Property<string>("DisplayName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GroupId")
						.HasColumnType("int");

					b.Property<string>("GroupName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty1")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty10")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty2")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty3")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty4")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty5")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty6")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty7")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty8")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("InstanceProperty9")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long>("LastCollectedTimeSeconds")
						.HasColumnType("bigint");

					b.Property<long>("LastUpdatedTimeSeconds")
						.HasColumnType("bigint");

					b.Property<DateTimeOffset?>("LastWentMissing")
						.HasColumnType("datetimeoffset");

					b.Property<bool>("LockDescription")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("SdtAt")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("SdtStatus")
						.HasColumnType("int");

					b.Property<bool>("StopMonitoring")
						.HasColumnType("bit");

					b.Property<string>("WildValue")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("WildValue2")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.HasIndex("DeviceDataSourceId");

					b.HasIndex("LastWentMissing");

					b.ToTable("DeviceDataSourceInstances");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<long>("AssignedOnSeconds")
						.HasColumnType("bigint");

					b.Property<long>("CreatedOnSeconds")
						.HasColumnType("bigint");

					b.Property<Guid>("DataSourceId")
						.HasColumnType("uniqueidentifier");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<Guid>("DeviceId")
						.HasColumnType("uniqueidentifier");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<long>("UpdatedOnSeconds")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("DataSourceId");

					b.HasIndex("DeviceId");

					b.ToTable("DeviceDataSources");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceGroupStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("AlertDisableStatus")
						.HasColumnType("int");

					b.Property<bool>("AlertEnable")
						.HasColumnType("bit");

					b.Property<int>("AlertStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatusPriority")
						.HasColumnType("int");

					b.Property<string>("AppliesTo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AutoVisualResult")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("AwsDeviceCount")
						.HasColumnType("int");

					b.Property<string>("AwsRegionsInfo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AwsTestResult")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("AwsTestResultCode")
						.HasColumnType("int");

					b.Property<int>("AzureDeviceCount")
						.HasColumnType("int");

					b.Property<string>("AzureRegionsInfo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("AzureTestResult")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("AzureTestResultCode")
						.HasColumnType("int");

					b.Property<string>("ClusterAlertStatus")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ClusterAlertStatusPriority")
						.HasColumnType("int");

					b.Property<int?>("CreatedOnTimestampUtc")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<int>("DefaultAgentId")
						.HasColumnType("int");

					b.Property<string>("DefaultCollectorDescription")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("DefaultCollectorId")
						.HasColumnType("int");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("DeviceCount")
						.HasColumnType("int");

					b.Property<int>("DeviceGroupType")
						.HasColumnType("int");

					b.Property<int>("DirectDeviceCount")
						.HasColumnType("int");

					b.Property<int>("DirectSubGroupCount")
						.HasColumnType("int");

					b.Property<bool>("EffectiveAlertEnabled")
						.HasColumnType("bit");

					b.Property<string>("FullPath")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GcpDeviceCount")
						.HasColumnType("int");

					b.Property<string>("GcpRegionsInfo")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("GcpTestResult")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GcpTestResultCode")
						.HasColumnType("int");

					b.Property<string>("GroupStatus")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("HasNetflowEnabledDevices")
						.HasColumnType("bit");

					b.Property<bool>("IsAlertingDisabled")
						.HasColumnType("bit");

					b.Property<bool>("IsNetflowEnabled")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ParentId")
						.HasColumnType("int");

					b.Property<int>("SdtStatus")
						.HasColumnType("int");

					b.Property<int>("UserPermission")
						.HasColumnType("int");

					b.HasKey("Id");

					b.ToTable("DeviceGroups");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("AlertDisableStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatusPriority")
						.HasColumnType("int");

					b.Property<bool>("AncestorHasDisabledLogicModule")
						.HasColumnType("bit");

					b.Property<long?>("AutoPropertiesAssignedOnSeconds")
						.HasColumnType("bigint");

					b.Property<long?>("AutoPropertiesUpdatedOnSeconds")
						.HasColumnType("bigint");

					b.Property<int>("AwsState")
						.HasColumnType("int");

					b.Property<int>("AzureState")
						.HasColumnType("int");

					b.Property<bool>("CanUseRemoteSession")
						.HasColumnType("bit");

					b.Property<string>("CollectorDescription")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<long?>("CreatedOnSeconds")
						.HasColumnType("bigint");

					b.Property<int>("CurrentCollectorId")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<long>("DeletedTimeInMs")
						.HasColumnType("bigint");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("DeviceGroupIdsString")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<byte>("DeviceStatus")
						.HasColumnType("tinyint");

					b.Property<int>("DeviceType")
						.HasColumnType("int");

					b.Property<string>("DisplayName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("EffectiveAlertEnabled")
						.HasColumnType("bit");

					b.Property<bool>("EnableNetflow")
						.HasColumnType("bit");

					b.Property<int>("GcpState")
						.HasColumnType("int");

					b.Property<bool>("HasActiveInstance")
						.HasColumnType("bit");

					b.Property<bool>("HasDisabledSubResource")
						.HasColumnType("bit");

					b.Property<bool>("HasMore")
						.HasColumnType("bit");

					b.Property<bool>("IsAlertingDisabled")
						.HasColumnType("bit");

					b.Property<long>("LastAlertClosedTimeSeconds")
						.HasColumnType("bigint");

					b.Property<long?>("LastDataTimeSeconds")
						.HasColumnType("bigint");

					b.Property<long?>("LastRawDataTimeSeconds")
						.HasColumnType("bigint");

					b.Property<long?>("LastTimeSeriesDataSyncDurationMs")
						.HasColumnType("bigint");

					b.Property<string>("Link")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("NetflowCollectorDescription")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("NetflowCollectorGroupId")
						.HasColumnType("int");

					b.Property<string>("NetflowCollectorGroupName")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("NetflowCollectorId")
						.HasColumnType("int");

					b.Property<Guid?>("PreferredCollectorId")
						.HasColumnType("uniqueidentifier");

					b.Property<string>("Property1")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property10")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property11")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property12")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property13")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property14")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property15")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property16")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property17")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property18")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property19")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property2")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property20")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property3")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property4")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property5")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property6")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property7")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property8")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Property9")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("RelatedDeviceId")
						.HasColumnType("int");

					b.Property<int>("ScanConfigId")
						.HasColumnType("int");

					b.Property<int>("SdtStatus")
						.HasColumnType("int");

					b.Property<long>("ToDeleteTimeInMs")
						.HasColumnType("bigint");

					b.Property<long?>("UpdatedOnSeconds")
						.HasColumnType("bigint");

					b.Property<int>("UptimeInSeconds")
						.HasColumnType("int");

					b.Property<int>("UserPermission")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("PreferredCollectorId");

					b.ToTable("Devices");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.TimeSeriesDataAggregationStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<double?>("AvailabilityPercent")
						.HasColumnType("float");

					b.Property<double?>("Centile05")
						.HasColumnType("float");

					b.Property<double?>("Centile10")
						.HasColumnType("float");

					b.Property<double?>("Centile25")
						.HasColumnType("float");

					b.Property<double?>("Centile50")
						.HasColumnType("float");

					b.Property<double?>("Centile75")
						.HasColumnType("float");

					b.Property<double?>("Centile90")
						.HasColumnType("float");

					b.Property<double?>("Centile95")
						.HasColumnType("float");

					b.Property<int?>("CriticalCount")
						.HasColumnType("int");

					b.Property<int>("DataCount")
						.HasColumnType("int");

					b.Property<Guid>("DeviceDataSourceInstanceDataPointId")
						.HasColumnType("uniqueidentifier");

					b.Property<int?>("ErrorCount")
						.HasColumnType("int");

					b.Property<double?>("First")
						.HasColumnType("float");

					b.Property<double?>("FirstWithData")
						.HasColumnType("float");

					b.Property<double?>("Last")
						.HasColumnType("float");

					b.Property<double?>("LastWithData")
						.HasColumnType("float");

					b.Property<double?>("Max")
						.HasColumnType("float");

					b.Property<double?>("Min")
						.HasColumnType("float");

					b.Property<int>("NoDataCount")
						.HasColumnType("int");

					b.Property<int?>("NormalCount")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("PeriodEnd")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("PeriodStart")
						.HasColumnType("datetimeoffset");

					b.Property<double>("Sum")
						.HasColumnType("float");

					b.Property<double>("SumSquared")
						.HasColumnType("float");

					b.Property<int?>("WarningCount")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("DeviceDataSourceInstanceDataPointId");

					b.ToTable("TimeSeriesDataAggregations");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.WebsiteGroupStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("AlertDisableStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatusPriority")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("DirectWebsiteCount")
						.HasColumnType("int");

					b.Property<int>("DirectWebsiteGroupCount")
						.HasColumnType("int");

					b.Property<bool>("DisableAlerting")
						.HasColumnType("bit");

					b.Property<string>("FullPath")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GroupStatus")
						.HasColumnType("int");

					b.Property<bool>("HasWebsitesDisabled")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ParentId")
						.HasColumnType("int");

					b.Property<int>("SdtStatus")
						.HasColumnType("int");

					b.Property<bool?>("StopMonitoring")
						.HasColumnType("bit");

					b.Property<int>("UserPermissionString")
						.HasColumnType("int");

					b.Property<int>("WebsiteCount")
						.HasColumnType("int");

					b.HasKey("Id");

					b.ToTable("WebsiteGroups");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.WebsiteStoreItem", b =>
				{
					b.Property<Guid>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("uniqueidentifier");

					b.Property<int>("AlertDisableStatus")
						.HasColumnType("int");

					b.Property<string>("AlertExpression")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("AlertStatus")
						.HasColumnType("int");

					b.Property<int>("AlertStatusPriority")
						.HasColumnType("int");

					b.Property<int>("Count")
						.HasColumnType("int");

					b.Property<DateTimeOffset>("DatamartCreated")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastModified")
						.HasColumnType("datetimeoffset");

					b.Property<DateTimeOffset>("DatamartLastObserved")
						.HasColumnType("datetimeoffset");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Domain")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GlobalSmAlertCond")
						.HasColumnType("int");

					b.Property<string>("HostName")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("IgnoreSsl")
						.HasColumnType("bit");

					b.Property<byte>("IndividualAlertLevel")
						.HasColumnType("tinyint");

					b.Property<bool>("IndividualSmAlertEnable")
						.HasColumnType("bit");

					b.Property<bool>("IsAlertingDisabled")
						.HasColumnType("bit");

					b.Property<bool>("IsInternal")
						.HasColumnType("bit");

					b.Property<int>("LogicMonitorId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<byte>("OverallAlertLevel")
						.HasColumnType("tinyint");

					b.Property<int>("PacketsNotReceivedTimeoutMs")
						.HasColumnType("int");

					b.Property<int>("PageLoadAlertTimeInMs")
						.HasColumnType("int");

					b.Property<int>("PercentPacketsNotReceiveInTime")
						.HasColumnType("int");

					b.Property<int>("PollingIntervalMinutes")
						.HasColumnType("int");

					b.Property<string>("Schema")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Script")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("SdtStatus")
						.HasColumnType("int");

					b.Property<int>("Status")
						.HasColumnType("int");

					b.Property<bool>("StopMonitoring")
						.HasColumnType("bit");

					b.Property<bool>("StopMonitoringByWebsiteGroup")
						.HasColumnType("bit");

					b.Property<int>("Transition")
						.HasColumnType("int");

					b.Property<bool>("TriggerSslExpirationAlerts")
						.HasColumnType("bit");

					b.Property<bool>("TriggerSslStatusAlerts")
						.HasColumnType("bit");

					b.Property<int>("Type")
						.HasColumnType("int");

					b.Property<bool>("UseDefaultAlertSetting")
						.HasColumnType("bit");

					b.Property<bool>("UseDefaultLocationSetting")
						.HasColumnType("bit");

					b.Property<int>("UserPermissionString")
						.HasColumnType("int");

					b.Property<Guid>("WebsiteGroupId")
						.HasColumnType("uniqueidentifier");

					b.Property<int>("WebsiteMethod")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("WebsiteGroupId");

					b.ToTable("Websites");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AlertRuleStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.EscalationChainStoreItem", "EscalationChain")
						.WithMany("AlertRules")
						.HasForeignKey("EscalationChainId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("EscalationChain");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AlertStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.AlertRuleStoreItem", "AlertRule")
						.WithMany("AlertStoreItems")
						.HasForeignKey("AlertRuleId")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup0")
						.WithMany("AlertsFromGroup0")
						.HasForeignKey("MonitorObjectGroup0Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup1")
						.WithMany("AlertsFromGroup1")
						.HasForeignKey("MonitorObjectGroup1Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup2")
						.WithMany("AlertsFromGroup2")
						.HasForeignKey("MonitorObjectGroup2Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup3")
						.WithMany("AlertsFromGroup3")
						.HasForeignKey("MonitorObjectGroup3Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup4")
						.WithMany("AlertsFromGroup4")
						.HasForeignKey("MonitorObjectGroup4Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup5")
						.WithMany("AlertsFromGroup5")
						.HasForeignKey("MonitorObjectGroup5Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup6")
						.WithMany("AlertsFromGroup6")
						.HasForeignKey("MonitorObjectGroup6Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup7")
						.WithMany("AlertsFromGroup7")
						.HasForeignKey("MonitorObjectGroup7Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup8")
						.WithMany("AlertsFromGroup8")
						.HasForeignKey("MonitorObjectGroup8Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.HasOne("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", "MonitorObjectGroup9")
						.WithMany("AlertsFromGroup9")
						.HasForeignKey("MonitorObjectGroup9Id")
						.OnDelete(DeleteBehavior.Restrict);

					b.Navigation("AlertRule");

					b.Navigation("MonitorObjectGroup0");

					b.Navigation("MonitorObjectGroup1");

					b.Navigation("MonitorObjectGroup2");

					b.Navigation("MonitorObjectGroup3");

					b.Navigation("MonitorObjectGroup4");

					b.Navigation("MonitorObjectGroup5");

					b.Navigation("MonitorObjectGroup6");

					b.Navigation("MonitorObjectGroup7");

					b.Navigation("MonitorObjectGroup8");

					b.Navigation("MonitorObjectGroup9");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.CollectorStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.CollectorGroupStoreItem", "CollectorGroup")
						.WithMany("Collectors")
						.HasForeignKey("CollectorGroupId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("CollectorGroup");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceDataPointStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.DataSourceGraphStoreItem", null)
						.WithMany("DataPoints")
						.HasForeignKey("DataSourceGraphStoreItemId");

					b.HasOne("LogicMonitor.Datamart.Models.DataSourceStoreItem", "DataSource")
						.WithMany()
						.HasForeignKey("DataSourceId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("DataSource");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceGraphStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.DataSourceStoreItem", "DataSource")
						.WithMany("Graphs")
						.HasForeignKey("DataSourceId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("DataSource");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceDataPointStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.DataSourceDataPointStoreItem", "DataSourceDataPoint")
						.WithMany("DeviceDataSourceInstanceDataPoints")
						.HasForeignKey("DataSourceDataPointId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("LogicMonitor.Datamart.Models.DataSourceStoreItem", null)
						.WithMany("DataPoints")
						.HasForeignKey("DataSourceStoreItemId");

					b.HasOne("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceStoreItem", "DeviceDataSourceInstance")
						.WithMany("DeviceDataSourceInstanceDataPoints")
						.HasForeignKey("DeviceDataSourceInstanceId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("DataSourceDataPoint");

					b.Navigation("DeviceDataSourceInstance");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.ResourceDataSourceStoreItem", "DeviceDataSource")
						.WithMany("DeviceDataSourceInstances")
						.HasForeignKey("DeviceDataSourceId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("DeviceDataSource");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.DataSourceStoreItem", "DataSource")
						.WithMany("DeviceDataSources")
						.HasForeignKey("DataSourceId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("LogicMonitor.Datamart.Models.ResourceStoreItem", "Device")
						.WithMany("DeviceDataSources")
						.HasForeignKey("DeviceId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("DataSource");

					b.Navigation("Device");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.CollectorStoreItem", "PreferredCollector")
						.WithMany("Devices")
						.HasForeignKey("PreferredCollectorId");

					b.Navigation("PreferredCollector");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.TimeSeriesDataAggregationStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceDataPointStoreItem", "DeviceDataSourceInstanceDataPoint")
						.WithMany("TimeSeriesDataAggregations")
						.HasForeignKey("DeviceDataSourceInstanceDataPointId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("DeviceDataSourceInstanceDataPoint");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.WebsiteStoreItem", b =>
				{
					b.HasOne("LogicMonitor.Datamart.Models.WebsiteGroupStoreItem", "WebsiteGroup")
						.WithMany("Websites")
						.HasForeignKey("WebsiteGroupId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.Navigation("WebsiteGroup");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.AlertRuleStoreItem", b =>
				{
					b.Navigation("AlertStoreItems");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.CollectorGroupStoreItem", b =>
				{
					b.Navigation("Collectors");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.CollectorStoreItem", b =>
				{
					b.Navigation("Devices");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceDataPointStoreItem", b =>
				{
					b.Navigation("DeviceDataSourceInstanceDataPoints");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceGraphStoreItem", b =>
				{
					b.Navigation("DataPoints");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.DataSourceStoreItem", b =>
				{
					b.Navigation("DataPoints");

					b.Navigation("DeviceDataSources");

					b.Navigation("Graphs");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.EscalationChainStoreItem", b =>
				{
					b.Navigation("AlertRules");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.MonitorObjectGroupStoreItem", b =>
				{
					b.Navigation("AlertsFromGroup0");

					b.Navigation("AlertsFromGroup1");

					b.Navigation("AlertsFromGroup2");

					b.Navigation("AlertsFromGroup3");

					b.Navigation("AlertsFromGroup4");

					b.Navigation("AlertsFromGroup5");

					b.Navigation("AlertsFromGroup6");

					b.Navigation("AlertsFromGroup7");

					b.Navigation("AlertsFromGroup8");

					b.Navigation("AlertsFromGroup9");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceDataPointStoreItem", b =>
				{
					b.Navigation("TimeSeriesDataAggregations");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceInstanceStoreItem", b =>
				{
					b.Navigation("DeviceDataSourceInstanceDataPoints");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceDataSourceStoreItem", b =>
				{
					b.Navigation("DeviceDataSourceInstances");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.ResourceStoreItem", b =>
				{
					b.Navigation("DeviceDataSources");
				});

			modelBuilder.Entity("LogicMonitor.Datamart.Models.WebsiteGroupStoreItem", b =>
				{
					b.Navigation("Websites");
				});
#pragma warning restore 612, 618
		}
	}
}
